name: Actualizar Rosco con IA
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Esto lo actualiza solo cada noche a las 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v2
        with:
          persist-credentials: true
      
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Generar nuevas preguntas aleatorias
        run: python generador.py
        
      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name 'IA-Generator'
          git config --global user.email 'ia@github.com'
          git add preguntas.json
          git commit -m "IA: Generando rosco nuevo aleatorio" || echo "Sin cambios para subir"
          git push
